plugins {
    id 'groovy'
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

group = 'dev.urth'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.apache.groovy:groovy-all:4.0.28'
    implementation 'ch.qos.logback:logback-classic:1.5.19'

    testImplementation platform('org.junit:junit-bom:6.0.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

javafx {
    version = '25'
    modules = ['javafx.controls', 'javafx.fxml']
}

application {
    mainClass = 'tabos.TabOS'
    applicationDefaultJvmArgs = [
        '--enable-native-access=javafx.graphics',
    ]
}

test {
    useJUnitPlatform()
    testLogging {
        events 'passed', 'skipped', 'failed'
    }
}
